#!/usr/bin/env Rscript
library("optparse")
library("magrittr")
source("scripts/phone_bank.R")

option_list = list(
  make_option(c("-o", "--out"), type="character", default="out.csv",
              help="output file name [default= %default]", metavar="character")
);

opt_parser = OptionParser(option_list=option_list);
opts = parse_args(opt_parser, positional_arguments = TRUE);

output_filename <- opts$options$out

print("Processing data files: ")
print(paste(opts$args))
input_filenames <- opts$args %>% as.list
df_processed <- prepare_phone_bank_files(input_filenames)

print(paste("Writing output to file: ", output_filename))
write.csv(df_processed, file=output_filename)
